{
 "title": "Database Exporter",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "database",
    "query": {
     "query": "label_values(pg_stat_database_numbackends,datname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Top-5 Tables by Rows",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(5, pg_stat_user_tables_n_live_tup{datname=~\"$database\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rollback rate (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_rollback{datname=~\"$database\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(pg_stat_database_numbackends{datname=~\"$database\"}) / 100) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Rows",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "rows" } },
   "targets": [
    {
     "expr": "sum(pg_stat_user_tables_n_live_tup{datname=~\"$database\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Tables",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pg_stat_user_tables_n_live_tup{datname=~\"$database\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions per second (5m rate)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=~\"$database\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime (hours)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds) / 3600\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Size (GB)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=~\"$database\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of active connections",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{datname=~\"$database\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PostgreSQL Availability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_up{instance=\"my_postgresql_db\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}