{
 "title": "Custom Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "city",
    "label": "City",
    "query": {
     "query": "label_values(weather_temperature_celsius,city)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Top 3 Avg Temperatures (1h)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(3, avg_over_time(weather_temperature_celsius[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rainfall vs Temperature Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ratio" } },
   "targets": [
    {
     "expr": "avg_over_time(weather_precipitation_mm[30m]) / avg_over_time(weather_temperature_celsius[30m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Wind Speed by City",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "expr": "avg(weather_windspeed_kmh) by (city)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Uptime Samples",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "count_over_time(weather_api_status{city=~\"$city\"}[30m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sum Temperature by Country",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(weather_temperature_celsius) by (country)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Response Time",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(weather_api_response_time_seconds{city=\"$city\",country=\"Kazakhstan\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Cloud Cover (6h",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(weather_cloud_cover_percent{city=\"$city\"}[6h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Pressure (1h)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(weather_pressure_hpa{city=\"$city\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature — 30m average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(weather_temperature_celsius{city=\"$city\"}[30m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature — current & history",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "weather_temperature_celsius{city=\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}